---
abstract: 'Text::CSV::Slurp - convert CSV into an array of hashes, or an array of hashes into CSV'
author:
  - 'BABF <babf@cpan.org>'
build_requires:
  Test::More: '0'
  Test::Most: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-CSV-Slurp
requires:
  IO::File: '0'
  Text::CSV: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/babf/Text-CSV-Slurp/issues
  repository: git://github.com/babf/Text-CSV-Slurp.git
version: '1.02'
