---
abstract: "convert CSV into an array of hashes, or an array of\nhashes into CSV"
author:
  - 'BABF <babf@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-Slurp
requires:
  IO::File: 0
  Test::Most: 0
  Text::CSV: 1.06
version: 1.0
